
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ryana/AppData/Local/Programs/Python/Python311/Lib/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
...
